# CAD Data Cleaning & Preparation
**Project:** Investigating Crisis Call Volumes — Eugene vs. Springfield  
**Author:** Ilhan Haniff  
**Description:** This notebook imports, cleans, and standardizes all Eugene CAD CSV files from 2015–2025, constructs temporal and agency classification features, and exports a single combined cleaned dataset for analysis.

**Input:** Raw yearly CAD CSV files (`data/EugeneCAD{year}noloc.csv`)  
**Output:** `data/cad_clean_2015_2025.csv`

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os

## 2. Load Raw Data
Import each yearly CAD file and combine into one raw DataFrame.

In [3]:
years = range(2015, 2026)
data_folder = 'data'

raw_frames = []

for year in years:
    filepath = os.path.join(data_folder, f'EugeneCAD{year}noloc.csv')
    df = pd.read_csv(filepath, low_memory=False)
    raw_frames.append(df)
    print(f'{year}: {df.shape[0]:,} rows loaded')

cad_raw = pd.concat(raw_frames, ignore_index=True)
print(f'\nTotal combined rows: {cad_raw.shape[0]:,}')
print(f'Columns: {list(cad_raw.columns)}')

2015: 123,248 rows loaded
2016: 127,732 rows loaded
2017: 129,688 rows loaded
2018: 127,432 rows loaded
2019: 137,089 rows loaded
2020: 137,287 rows loaded
2021: 137,527 rows loaded
2022: 140,545 rows loaded
2023: 135,464 rows loaded
2024: 132,650 rows loaded
2025: 117,352 rows loaded

Total combined rows: 1,446,014
Columns: ['yr', 'agency', 'service', 'inci_id', 'calltime', 'case_id', 'callsource', 'nature', 'closecode', 'closed_as', 'secs_to_disp', 'secs_to_arrv', 'secs_to_close', 'disp', 'arrv', 'priority', 'primeunit', 'units_dispd', 'units_arrived', 'month']

## 3. Initial Inspection

In [6]:
# First few rows
cad_raw.head()

,yr,agency,service,inci_id,calltime,case_id,callsource,nature,closecode,closed_as,secs_to_disp,secs_to_arrv,secs_to_close,disp,arrv,priority,primeunit,units_dispd,units_arrived,month
0,2015,EPD,LAW,15000001,2015-01-01 00:00:00.000,NaN,SELF,PERSON STOP,ASST,ASSISTED,0.0,0.0,217,1,1,6,_5E48,1,1,NaN
1,2015,EPD,LAW,15000002,2015-01-01 00:00:44.000,NaN,SELF,FIGHT,RSLV,RESOLVED,0.0,0.0,2114,1,1,P,_3F65,4,2,NaN
2,2015,EPD,LAW,15000003,2015-01-01 00:01:05.000,NaN,PHONE,CHECK WELFARE,ASST,ASSISTED,708.0,1094.0,1538,1,1,5,_3J79,1,1,NaN
3,2015,EPD,LAW,15000007,2015-01-01 00:03:16.000,NaN,W911,SHOTS FIRED,PCHK,PATROL CHECK,277.0,576.0,891,1,1,3,_5E48,2,2,NaN
4,2015,EPD,LAW,15000010,2015-01-01 00:03:34.000,NaN,SELF,ILLEGAL FIREWORKS,ADVI,ADVISED,0.0,0.0,150,1,1,5,_5K97,1,1,NaN

In [7]:
# Data types
cad_raw.dtypes

yr                 int64
agency            object
service           object
inci_id            int64
calltime          object
case_id           object
callsource        object
nature            object
closecode         object
closed_as         object
secs_to_disp     float64
secs_to_arrv     float64
secs_to_close      int64
disp               int64
arrv               int64
priority          object
primeunit         object
units_dispd        int64
units_arrived      int64
month            float64
dtype: object

In [8]:
# Missing value counts per column
cad_raw.isnull().sum()

yr                     0
agency                 0
service                0
inci_id                0
calltime               0
case_id          1213169
callsource             5
nature                53
closecode              0
closed_as          23928
secs_to_disp      414622
secs_to_arrv      532540
secs_to_close          0
disp                   0
arrv                   0
priority               0
primeunit         354283
units_dispd            0
units_arrived          0
month            1328662
dtype: int64

## 4. Select Relevant Columns
Keep only the columns relevant to the research questions.

In [45]:
cols_to_keep = ['agency', 'inci_id', 'calltime', 'primeunit']

cad = cad_raw[cols_to_keep].copy()
print(f'New Shape: {cad.shape}')

New Shape: (1446014, 4)

In [46]:
# First few rows
cad.head(5)

  agency   inci_id                 calltime primeunit
0   EPD   15000001  2015-01-01 00:00:00.000   _5E48
1   EPD   15000002  2015-01-01 00:00:44.000   _3F65
2   EPD   15000003  2015-01-01 00:01:05.000   _3J79
3   EPD   15000007  2015-01-01 00:03:16.000   _5E48
4   EPD   15000010  2015-01-01 00:03:34.000   _5K97

## 5. Standardize Variable Names and Text
Rename columns for consistency, strip whitespace from all string columns.

In [47]:
# Strip leading/trailing whitespace from all string columns
str_cols = cad.select_dtypes(include='object').columns
for col in str_cols:
    cad[col] = cad[col].str.strip()

# Standardize text to uppercase for consistency
for col in ['agency', 'primeunit']:
    cad[col] = cad[col].str.upper()

print('String columns cleaned:', list(str_cols))
print('Unique agency values after cleaning:', cad['agency'].unique())

String columns cleaned: ['agency', 'calltime', 'primeunit']
Unique agency values after cleaning: ['EPD' 'CAHE']

## 6. Convert calltime to Datetime and Extract Temporal Features

In [48]:
# Convert calltime to datetime
cad['calltime'] = pd.to_datetime(cad['calltime'], errors='coerce')

# Report any rows where conversion failed
failed = cad['calltime'].isna().sum()
print(f'Rows with missing calltime: {failed}')

# Extract temporal features
cad['call_year']  = cad['calltime'].dt.year
cad['call_month'] = cad['calltime'].dt.month
cad['call_day']   = cad['calltime'].dt.day
cad['call_hour']  = cad['calltime'].dt.hour
cad['call_dow']   = cad['calltime'].dt.day_name()  # day of week

cad.head(5)

Rows with missing calltime: 0

,agency,inci_id,calltime,primeunit,call_year,call_month,call_day,call_hour,call_dow
0,EPD,15000001,2015-01-01 00:00:00,_5E48,2015,1,1,0,Thursday
1,EPD,15000002,2015-01-01 00:00:44,_3F65,2015,1,1,0,Thursday
2,EPD,15000003,2015-01-01 00:01:05,_3J79,2015,1,1,0,Thursday
3,EPD,15000007,2015-01-01 00:03:16,_5E48,2015,1,1,0,Thursday
4,EPD,15000010,2015-01-01 00:03:34,_5K97,2015,1,1,0,Thursday

## 7. Classify Unit Type (agency classification)

The `agency` column explicitly identifies CAHOOTS only from 2022 onward (`'CAHE'`). For earlier years (2015–2021), CAHOOTS units are identified by `'J'` in the `primeunit` field (e.g., `_3J79`). All other units are classified as EPD or other.

Classification rules:
- `agency == 'CAHE'` → `'CAHOOTS'`
- `agency == 'EPD'` AND `'J'` in primeunit → `'CAHOOTS'`
- Missing primeunit → `'UNKNOWN'`
- All remaining EPD units → `'EPD'`

In [57]:
# Preview primeunit and agency patterns to inform classification
print('Sample primeunit values:')
print(cad['primeunit'].dropna().unique()[:1000])
print('Sample agency values:')
print(cad['agency'].dropna().unique()[:20])

Sample primeunit values:
['_5E48' '_3F65' '_3J79' '_5K97' '_4E31' '_4X40' '_5E57' '_3F68' '_1E53'
 '_4E81' '_6E28' '_6E97' '_4U71' '_6E15' '_6B36' '_AWO' '_5E58' '_4B51'
 '_5E65' '_5B44' '_4B11' '_5B62' '_5T84' '_CMD8' '_CAHOT' '_4X41' '_4E54'
 '_5B81' '_4B61' '_6X60' '_6T86' '_4F72' '_2U26' '_1F64' '_1E44' '_1M13'
 '_2E34' '_1E57' '_3E46' '_2E14' '_2Y35' '_3E48' '_3J78' '_3E55' '_3E18'
 '_3E58' '_3F67' '_3E29' '_3E39' '_3E25' '_1M15' '_3E16' '_2K81' '_4T88'
 '_4E91' '_4E61' '_4E12' '_4E51' '_4E42' '_3X30' '_4F73' '_6E16' '_5E88'
 '_CMD9' '_5E66' '_5E46' '_6E29' '_6E38' '_5E55' '_1D12' '_1E67' '_1E51'
 '_2C82' '_2R17' '_2Y16' '_3W73' '_CNTR' '_3F61' '_2Y12' '_3W79' '_4E53'
 '_5T83' '_SLT1' '_2X20' '_4E93' '_4E52' '_5T82' '_5T81' '_4E13' '_1E54'
 '_1E43' '_3U38' '_2E21' '_2E94' '_3E19' '_1E69' '_2E92' '_3E49' '_2C81'
 '_2E35' '_3E26' '_3E68' '_3V78' '_3W74' '_3E45' '_3E59' '_3E56' '_CMD2'
 '_3X90' '_4E43' '_4E11' '_5E51' '_5E62' '_2R13' '_5E47' '_6E35' '_6E26'
 '_6E19' '_1F66' '_1X11' '_1E52' '_3E88' '_1E65' '_SLT3' '_2Y45' '_3E95'
 '_4S43' '_2K85' '_4E63' '_4K91' '_5E45' '_1D11' '_1F62' '_2P11' '_1M11'
 '_2P15' '_2P12' '_2P14' '_SLT2' '_2E11' '_2Y43' '_1M12' '_2Y49' '_2E12'
 '_5U47' '_5U81' '_3B46' '_2E22' '_2Y48' '_5B53' '_1X10' '_2Y33' '_4B31'
 '_6E36' '_STF10' '_2Y90' '_2Y40' '_2P13' '_2Y92' '_4K98' '_5E85' '_EP279'
 '_3B55' '_6E96' '_5E11' '_5X50' '_CMD6' '_5E56' '_5E33' '_6T84' '_2E13'
 '_3U45' '_1E83' '_3E38' '_3W75' '_4E33' '_3X31' '_5K98' '_2K87' '_2Z22'
 '_2Z20' '_2Z21' '_2Z23' '_2R14' '_2R91' '_2X21' '_1M10' '_2K83' '_4E21'
 '_4E14' '_3U95' '_5Z51' '_5Z52' '_5X51' '_2Y47' '_1E55' '_3E69' '_2Y46'
 '_3E36' '_1B42' '_2Y15' '_3B25' '_3U88' '_4E23' '_6B96' '_5U58' '_1E42'
 '_CMD1' '_4F71' '_2Y41' '_4E34' '_1300' '_1E81' '_1U43' '_EP225' '_EP482'
 '_5B51' '_2P10' '_4K95' '_2E26' '_4E44' '_4E32' '_2Y31' '_3D11' '_2Y18'
 '_EP125' '_5U55' '_6B23' '_4Z41' '_6E25' '_1S12' '_1S11' '_EP624' '_5U57'
 '_4E41' '_5Z53' '_5Z55' '_1500' '_5Z54' '_5U85' '_3D13' '_4X43' '_3Z69'
 '_6Z67' '_1Z64' '_6Z66' '_3Z68' '_5Z63' '_5E24' '_6Z65' '_1T12' '_2E33'
 '_1M14' '_1B84' '_CMD5' '_2Y44' '_5E93' '_3X32' '_5E42' '_2Y11' '_2Y19'
 '_2K82' '_3F62' '_5U62' '_5Z86' '_5B64' '_4Z52' '_5U51' '_1M17' '_6U95'
 '_1Z14' '_1Z10' '_1Z13' '_5B83' '_2G19' '_6U19' '_K98' '_3U26' '_STF1'
 '_6X61' '_2Y91' '_1H64' '_1H62' '_6B95' '_3S13' '_1U62' '_EP622' '_1U57'
 '_3B84' '_EP100' '_1T11' '_EP367' '_EP329' '_1301' '_4Z42' '_4Z43'
 '_4Z44' '_5E23' '_5Z50' '_EP648' '_1302' '_2B92' '_3E94' '_2Z11' '_2Y13'
 '_EP474' '_4E82' '_3E86' '_5B61' '_EP395' '_1Z57' '_2Y42' '_3Z32' '_3E35'
 '_3H95' '_3H88' '_2B91' '_2X22' '_3Z33' '_3Z37' '_3Z36' '_3E96' '_SST1'
 '_3Z88' '_3Z35' '_3Z31' '_2Y14' '_2R12' '_1Z53' '_5E13' '_CMD10' '_2Y53'
 '_2R16' '_1E64' '_5E64' '_3Z26' '_EP124' '_STF33' '_1U51' '_3B45' '_5Z56'
 '_6Z11' '_5Z58' '_3H42' '_6U97' '_1H61' '_1303' '_5E43' '_2Y17' '_EP658'
 '_5K95' '_1H60' '_EP639' '_5E94' '_4E22' '_3H41' '_3B56' '_3B26' '_6Z13'
 '_5B85' '_6U35' '_3F66' '_3E15' '_C1' '_EP167' '_4F62' '_Z1' '_1M16'
 '_3U58' '_SLT4' '_3H40' '_3H48' '_5X53' '_EP151' '_3H49' '_5H44' '_3E89'
 '_2Y10' '_4B21' '_6T83' '_3U25' '_5E21' '_6E98' '_3S22' '_EP348' '_6E58'
 '_6E46' '_6E95' '_3Z30' '_3F72' '_4Z40' '_1E41' '_CMD3' '_5E31' '_5B14'
 '_5E61' '_5Z90' '_2K86' '_4H31' '_3B87' '_3Z58' '_3B85' '_5B41' '_6B11'
 '_4H32' '_5E32' '_6T87' '_4H33' '_EDU10' '_EDU11' '_2E83' '_EP610'
 '_6H31' '_3U68' '_5H42' '_6E86' '_EP371' '_EP601' '_4H34' '_2H31' '_4E94'
 '_3S11' '_2L63' '_1H21' '_2E93' '_4E24' '_1F65' '_4B71' '_5E12' '_5Z94'
 '_5Z91' '_5Z93' '_2H32' '_2E91' '_5B82' '_3E28' '_6B15' '_1F61' '_3H31'
 '_EP119' '_6E49' '_3B88' '_5B54' '_3D1' '_3H47' '_3U49' '_3H46' '_EP385'
 '_1U69' '_3U46' '_1T14' '_E1' '_6E87' '_DEF' '_1U82' '_3U55' '_6Z12'
 '_2C10' '_2H33' '_2U35' '_1E84' '_1306' '_5B46' '_2L70' '_1U52' '_3B16'
 '_Z18' '_Z65' '_Z74' '_Z68' '_Z66' '_Z71' '_Z69' '_Z67' '_Z75' '_Z42'
 '_Z13' '_Z35' '_Z73' '_Z12' '_L21' '_Z36' '_Z27' '_Z4' '_Z3' '_Z63'
 '_Z28' '_Z43' '_Z19' '_Z15' '_Z44' '_2U21' '_2W74' '_6H62' '_2U11'
 '_3B96' '_3B69' '_3Z34' '_EP651' '_6Z45' '_Z34' '_Z11' '_Z2' '_Z64'
 '_Z14' '_Z37' '_Z72' '_Z20' '_Z26' '_6H61' '_1T15' '_3U59' '_4Z45'
 '_3U69' '_Z76' '_Z61' '_Z32' '_Z82' '_Z81' '_Z16' '_2M2' '_Z22' '_Z77'
 '_Z78' '_Z24' '_Z79' '_Z33' '_Z23' '_Z38' '_EP404' '_3U96' '_3E84' '_Z50'
 '_Z31' '_Z9' '_2C80' '_1S10' '_3E65' '_6U15' '_EPRECS' '_2G16' '_4Z11'
 '_1900' '_3F73' '_5Z85' '_4E83' '_Z62' '_Z21' '_Z54' '_Z49' '_EP602'
 '_5U56' '_5E22' '_2G14' '_5E87' '_Z6' '_Z30' '_4E92' '_2U13' '_3U19'
 '_4E64' '_1U42' '_3U23' '_1U44' '_Z8' '_Z51' '_Z52' '_6Z82' '_6Z81'
 '_5E53' '_EP647' '_5E83' '_6Z86' '_2Z24' '_4U91' '_3U29' '_4U94' '_4U41'
 '_EP365' '_3U24' '_5Z11' '_3U56' '_1600' '_5B43' '_5E92' '_2B94' '_2B11'
 '_2E27' '_CMD4' '_6E37' '_2Z92' '_TEST' '_2E98' '_3U98' '_3U18' '_STF20'
 '_3F63' '_3E54' '_1B81' '_K94' '_4U83' '_EP623' '_5B52' '_4U81' '_4F52'
 '_3F69' '_1Z11' '_3E97' '_5E14' '_EP641' '_1U54' '_6U96' '_1T16' '_1B82'
 '_2E37' '_6B98' '_TEST1' '_5E44' '_4F66' '_3B86' '_1T13' '_5E82' '_WLM'
 '_3B35' '_3Z39' '_3Z38' '_1B52' '_5C6' '_HAF' '_1U41' '_4U24' '_2M1'
 '_1400' '_2R15' '_2L60' '_6U26' '_2D11' '_3J77' '_1S19' '_W9' '_S2'
 '_EP146' '_1H22' '_2S11' '_2L62' '_1U81' '_W6' '_2R18' '_2U34' '_1B64'
 '_EP400' '_2U27' '_6E56' '_1B41' '_H30' '_Z87' '_Z17' '_EP333' '_4Z24'
 '_EP270' '_2H35' '_2H34' '_H41' '_H42' '_H37' '_H43' '_H33' '_H34'
 '_6H38' '_6Z98' '_2Z26' '_Z10' '_Z29' '_Z39' '_Z53' '_2Z27' '_4T85'
 '_EP115' '_EP105' '_6E18' '_Z5' '_2H36' '_2H37' '_5H41' '_5H43' '_3W77'
 '_2Z94' '_1E92' '_2L69' '_3Z18' '_1F74' '_6B25' '_4E84' '_5E91' '_1307'
 '_2M3' '_3W78' '_3Z53' '_2G10' '_2U91' '_1U65' '_130' '_2G17' '_2E81'
 '_6Z95' '_Z40' '_6U25' '_2Y9' '_6U37' '_3E85' '_2W77' '_2U94' '_1308'
 '_Z7' '_Z70' '_Z57' '_2Y09' '_5E86' '_3B15' '_5F65' '_3H43' '_3U86'
 '_E11' '_2B22' '_EP120' '_5Z22' '_4Z81' '_3Z11' '_3Z13' '_3U84' '_3Z12'
 '_EP425' '_1Z12' '_2W78' '_STF35' '_1407' '_2B12' '_3U48' '_5E63' '_5E52'
 '_5H61' '_2K80' '_EP605' '_5U42' '_1305' '_1F68' '_EP244' '_1B51' '_5U86'
 '_3E61' '_3E33' '_3E32' '_1E37' '_6E57' '_1E11' '_6Z26' '_1X12' '_5Z57'
 '_1F71' '_2E47' '_2E64' '_2E23' '_3E63' '_2E17' '_3E62' '_6U45' '_3E31'
 '_3E44' '_4E62' '_6E61' '_6E45' '_EP462' '_5E35' '_1F72' '_1E25' '_1E24'
 '_6E55' '_6E14' '_6E27' '_2E36' '_2E48' '_2E53' '_3E57' '_4E67' '_4E55'
 '_6E31' '_5E34' '_5E19' '_2E51' '_2E18' '_2E49' '_4E37' '_2Z33' '_3W76'
 '_6K91' '_4E68' '_4E56' '_6Z22' '_1F73' '_1B65' '_1J77' '_4T86' '_1Z84'
 '_3X33' '_5Z21' '_3U31' '_3U65' '_3U15' '_4E25' '_4E26' '_2Y34' '_6E44'
 '_3E27' '_1E26' '_2B18' '_5B22' '_5U63' '_5E17' '_5U22' '_5E49' '_5U66'
 '_3E14' '_EP645' '_EP662' '_6B57' '_3U63' '_1U33' '_6U65' '_6E59' '_1E12'
 '_3U33' '_4B85' '_5B33' '_5U53' '_CMD03' '_5U44' '_1E33' '_EP341' '_5U35'
 '_3F75' '_3F76' '_5E18' '_4E38' '_3D12' '_6U46' '_2Z25' '_CMD7' '_1S13'
 '_6E62' '_1U11' '_3H64' '_3J76' '_2P16' '_1U21' '_EP472' '_4U11' '_STF40'
 '_1U67' '_1S18' '_2E65' '_6U61' '_2U22' '_2L64' '_6E67' '_EP646' '_5Z92'
 '_2U23' '_1U37' '_64E45' '_EP616' '_3E66' '_3B28' '_5B23' '_6U57'
 '_EP628' '_EP324' '_EP679' '_EP104' '_EP255' '_2B51' '_6B68' '_&'
 '_EP401' '_EP359' '_4B42' '_2S18' '_2Z34' '_3U44' '_EP118' '_6B67'
 '_5Z66' '_3U62' '_1E56' '_3Z55' '_1E13' '_2B43' '_EP107' '_5B34' '_1E39'
 '_1H23' '_1452' '_5E41' '_2B85' '_3S12' '_5T86' '_3U28' '_EP636' '_4U52'
 '_3E99' '_3U32' '_Z46' '_STF14' '_Z41' '_Z25' '_2E19' '_Z60' '_Z45'
 '_Z97' '_Z99' '_EP1100' '_Z80' '_Z96' '_1E68' '_EP1102' '_6E48' '_1311'
 '_Z999' '_4U37' '_6U29' '_5B21' '_TEST2' '_1B83' '_1U22' '_1U24' '_EP667'
 '_6E65' '_5B31' '_3D14' '_6B48' '_5Z34' '_5Z33' '_EP650' '_EP357' '_1B37'
 '_2G12' '_3W72' '_2E52' '_2W76' '_4E69' '_6E32' '_3E53' '_1F67' '_3F71'
 '_3E24' '_2E66' '_5E29' '_3Z44' '_1F63' '_2S12' '_3E34' '_3X36' '_3E47'
 '_4B66' '_5E16' '_3Z23' '_3E51' '_2B56' '_3B21' '_6Z57' '_3E21' '_5B29'
 '_4K97' '_EP608' '_4E66' '_3E17' '_4E36' '_3B89' '_5B63' '_6U58' '_EP696'
 '_5B12' '_3B51' '_1U68' '_2Z18' '_6B37' '_3Z28' '_5B11' '_4Z36' '_2U56'
 '_3Z43' '_3U16' '_2Z13' '_2B31' '_4Z49' '_3U51' '_2Z14' '_4Z19' '_3B58'
 '_Z98' '_EP463']
Sample agency values:
['EPD' 'CAHE']

In [63]:
def classify_unit(row):
    """
    Classifies each call's responding unit type based on agency and primeunit.
    
    Returns one of: 'CAHOOTS', 'EPD', or 'UNKNOWN'
    """
    agency = str(row['agency']).strip() if pd.notna(row['agency']) else ''
    unit_missing = pd.isna(row['primeunit'])
    unit = str(row['primeunit']).strip() if not unit_missing else ''

    # Missing primeunit — cannot classify
    if unit_missing:
        return 'UNKNOWN'

    
    # Explicit CAHOOTS agency label (2022+)
    if agency == 'CAHE':
        return 'CAHOOTS'

    # CAHOOTS identified by 'J' in primeunit (pre-2022)
    if agency == 'EPD' and 'J' in unit:
        return 'CAHOOTS'

    # All remaining EPD units
    return 'EPD'

cad['unit_type'] = cad.apply(classify_unit, axis=1)
cad = cad.drop(columns='agency')

print('unit_type value counts:')
print(cad['unit_type'].value_counts())

unit_type value counts:
unit_type
EPD        933692
UNKNOWN    354283
CAHOOTS    158039
Name: count, dtype: int64

In [64]:
# Verify CAHOOTS classification by year — should be > 0 for 2015-2021
print('CAHOOTS calls by year:')
print(cad[cad['unit_type'] == 'CAHOOTS'].groupby('call_year').size())

CAHOOTS calls by year:
call_year
2015     9547
2016    10989
2017    14122
2018    15055
2019    16414
2020    16534
2021    16746
2022    20317
2023    17354
2024    16532
2025     4429
dtype: int64

## 8. Check for Duplicates and Missing Values

In [65]:
# Check for duplicate incident IDs
dupes = cad.duplicated(subset=['inci_id']).sum()
print(f'Duplicate inci_id rows: {dupes}')

# Missing values summary
print('\nMissing values per column:')
print(cad.isnull().sum())

Duplicate inci_id rows: 0

Missing values per column:
inci_id            0
calltime           0
primeunit     354283
call_year          0
call_month         0
call_day           0
call_hour          0
call_dow           0
unit_type          0
dtype: int64

In [66]:
# Note: primeunit missing values are kept — some calls may not have a unit assigned.
# These will show as 'UNKNOWN' in unit_type

print(f"Rows with missing primeunit: {cad['primeunit'].isna().sum()}")
print(f"Rows classified as UNKNOWN: {(cad['unit_type'] == 'UNKNOWN').sum()}")

Rows with missing primeunit: 354283
Rows classified as UNKNOWN: 354283

## 9. Final Dataset Summary

In [67]:
print('=== Final Cleaned Dataset Summary ===')
print(f'Shape: {cad.shape}')
print(f'Date range: {cad["calltime"].min()} to {cad["calltime"].max()}')
print(f'\nColumns: {list(cad.columns)}')
print(f'\nunit_type distribution:')
print(cad['unit_type'].value_counts())
print(f'\nCalls per year:')
print(cad.groupby('call_year').size())

=== Final Cleaned Dataset Summary ===
Shape: (1446014, 9)
Date range: 2015-01-01 00:00:00 to 2025-12-31 23:56:03

Columns: ['inci_id', 'calltime', 'primeunit', 'call_year', 'call_month', 'call_day', 'call_hour', 'call_dow', 'unit_type']

unit_type distribution:
unit_type
EPD        933692
UNKNOWN    354283
CAHOOTS    158039
Name: count, dtype: int64

Calls per year:
call_year
2015    123248
2016    127732
2017    129688
2018    127432
2019    137089
2020    137287
2021    137527
2022    140545
2023    135464
2024    132650
2025    117352
dtype: int64

In [68]:
# Preview final dataset
cad.head()

,inci_id,calltime,primeunit,call_year,call_month,call_day,call_hour,call_dow,unit_type
0,15000001,2015-01-01 00:00:00,_5E48,2015,1,1,0,Thursday,EPD
1,15000002,2015-01-01 00:00:44,_3F65,2015,1,1,0,Thursday,EPD
2,15000003,2015-01-01 00:01:05,_3J79,2015,1,1,0,Thursday,CAHOOTS
3,15000007,2015-01-01 00:03:16,_5E48,2015,1,1,0,Thursday,EPD
4,15000010,2015-01-01 00:03:34,_5K97,2015,1,1,0,Thursday,EPD

## 10. Export Cleaned Dataset

In [69]:
output_path = os.path.join(data_folder, 'cad_clean_2015_2025.csv')
cad.to_csv(output_path, index=False)
print(f'Cleaned dataset saved to: {output_path}')
print(f'Final shape: {cad.shape}')

Cleaned dataset saved to: data/cad_clean_2015_2025.csv
Final shape: (1446014, 9)